### PR TITLE
Replace - with _ for blade component directives

### PR DESCRIPTION
**Pull request by aremu-smog**
#2 
This fixes the installation issues

### CODE REVIEW

**Comment by unicodeveloper** [comment]
Thanks for submitting this fix @aremu-smog

**Comment by unicodeveloper** [comment]
@aremu-smog I am a little curious.

In what environment, did you get this issue? https://github.com/cloudinary-labs/cloudinary-laravel/issues/2

What laravel version and at what point of  installation? I don't get this issue on a fresh installation for Laravel 7.

**Comment by aremu-smog** [comment]
I got the issue with laravel 6

**Comment by aremu-smog** [comment]
Hi @unicodeveloper , 

I got issue #2 in laravel 6.*

The issue occurs when optimized autoload files are being generated

I also tried installing the package on a fresh installation of Laravel  7 and it works but still doesn't work on Laravel 6.*

**Pull request closed without merging**
